spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.1.24:3306/journals?createDatabaseIfNotExist=true
    username: mymysql
    password: mymysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
multipart:
  max-file-size: 1MB
  max-request-size: 1MB

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://rdb:3306/journals?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
multipart:
  max-file-size: 1MB
  max-request-size: 1MB

